FROM node:18-alpine AS build
WORKDIR /app
COPY package-lock.json package.json ./
RUN npm install --frozen-lockfile
COPY . .
RUN npm run build && \
    rm -rf node_modules

FROM node:18-alpine AS deps
WORKDIR /app
COPY package-lock.json package.json ./
RUN npm install --production --frozen-lockfile

FROM node:18-alpine AS runner
ENV NODE_ENV production
ENV NODE_OPTIONS "--max-old-space-size=8192"
ENV APP_PORT 8080
EXPOSE $APP_PORT
WORKDIR /app
COPY --from=build /app/dist ./dist
COPY --from=deps /app/node_modules ./node_modules
COPY yarn.lock package.json ./
COPY .env.production .env.production
CMD ["npm", "start"]
