version: '3'
services:
  postgres:
    image: postgres:12.2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=postgres
    volumes:
      - liviu-db-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    ports:
      - '8080:8080'
    restart: unless-stopped

volumes:
  liviu-db-data:
